apps/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = "accounts"

urlpatterns = [
    # login, register, logout cukup panggil as_view() tanpa parameter
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # URL statis tanpa regex
    path('account/result.html', views.account_result, name='result'),
]

apps/blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(r'blogs.html', views.IndexView.as_view(), name='index'),
    path(r'npage/<int:page>/', views.IndexView.as_view(), name='index_page'),

    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>/<slug:slug>.html',
         views.ArticleDetailView.as_view(),
         name='detailbyid'),

    path(r'category/<slug:category_name>.html', views.CategoryDetailView.as_view(), name='category_detail'),
    path(r'category/<slug:category_name>/<int:page>.html', views.CategoryDetailView.as_view(),
         name='category_detail_page'),

    path(r'author/<author_name>.html', views.AuthorDetailView.as_view(), name='author_detail'),
    path(r'author/<author_name>/<int:page>.html', views.AuthorDetailView.as_view(),
         name='author_detail_page'),

    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'tag/<slug:tag_name>/<int:page>.html', views.TagDetailView.as_view(), name='tag_detail_page'),
    path(r'archives.html', cache_page(60 * 60)(views.ArchivesView.as_view()), name='archives'),
    path(r'links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
    path(r'refresh', views.refresh_memcache, name='refresh')

]

apps/comment/urls.py
from django.urls import path
from .views import *

app_name="comment"

urlpatterns = [
    path('update_comment', update_comment, name ='update_comment'),
]


teknusa/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include, re_path
from accounts import views
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from teknusa.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from teknusa.feeds import AgrositeFeed
from django.views.generic import TemplateView
from ckeditor_uploader import urls as ckeditor_urls
from ckeditor_uploader import views as ckeditor_uploader_views


sitemaps = {
    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handler403 = 'blog.views.permission_denied_view'  # perbaiki typo: handle403 -> handler403

urlpatterns = [
    path('admin/', admin.site.urls),   # <--- tambahkan ini

    path('mdeditor/', include('mdeditor.urls')),
    path('cookies/', include('cookie_consent.urls')),
    # path('', include('notice.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('home.urls')),
    path('', include('apps.contactus.urls')),
    path('', include('about.urls')),
    # path('', include('apps.careers.urls')),
    path('', include('services.urls')),
    path('', include('portfolio.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path("likes/", include(('likeunlike.urls', 'likeunlike'), namespace="likes")),
    path('summernote/', include('django_summernote.urls')),

    # sitemap pakai re_path karena regex
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    path('feed/', AgrositeFeed()),
    path('rss/', AgrositeFeed()),
    path('comment/', include('comment.urls')),
    path('', include('accounts.urls', namespace='account')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('lean/', include('lean.urls')),
    path('ledger/', include('ledger.urls')),
    path('post_media/', include('post_media.urls')),
    path('search/', include('haystack.urls'), name='search'),
    path('ckeditor/', include(ckeditor_urls)),  # Ensure ckeditor URLs are included
    path('ckeditor/upload/', ckeditor_uploader_views.upload, name='ckeditor_upload'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/forms.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence 
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: forms.py
@time: 2017/1/7 上午12:36
"""

from haystack.forms import SearchForm
from django import forms
import logging

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

apps/blog/views.py
from django.shortcuts import render

# Create your views here.
import os
import datetime
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from django import forms
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from teknusa.utils import cache, get_md5, get_blog_setting
from django.shortcuts import get_object_or_404
from blog.models import Article, Category, Tag, Links
from comment.form import CommentForm
import logging

logger = logging.getLogger(__name__)


class ArticleListView(ListView):

    template_name = 'blog/blogs.html'

    context_object_name = 'article_list'

    page_type = ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg = 'page'
    link_type = 'l'

    def get_view_cache_key(self):
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        Subclass rewriting. Obtain the cache key of queryset
        """
        raise NotImplementedError()

    def get_queryset_data(self):
        """
        Subclass rewrite. Get data from queryset
        """
        raise NotImplementedError()

    def get_queryset_from_cache(self, cache_key):
        '''
        Cache page data
        :param cache_key: cache key
        :return:
        '''
        value = cache.get(cache_key)
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key, article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        '''
        Rewrite the default, get data from the cache
        :return:
        '''
        key = self.get_queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value

    def get_context_data(self, **kwargs):
        kwargs['linktype'] = self.link_type
        return super(ArticleListView, self).get_context_data(**kwargs)


class IndexView(ArticleListView):
    '''
    Home
    '''
    # Friendly link type
    link_type = 'i'

    def get_queryset_data(self):
        article_list = Article.objects.filter(type='a', status='p', is_removed=False)
        return article_list

    def get_queryset_cache_key(self):
        cache_key = 'index_{page}'.format(page=self.page_number)
        return cache_key


class ArticleDetailView(DetailView):
    '''
    Article details page
    '''
    template_name = 'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        articleid = int(self.kwargs[self.pk_url_kwarg])
        comment_form = CommentForm()
        user = self.request.user
        

        article_comments = self.object.comment_list()

        kwargs['form'] = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(article_comments) if article_comments else 0

        kwargs['next_article'] = self.object.next_article
        kwargs['prev_article'] = self.object.prev_article

        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryDetailView(ArticleListView):
    '''
    Category List
    '''
    page_type = "Catalog archive"

    def get_queryset_data(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)

        categoryname = category.name
        self.categoryname = categoryname
        categorynames = list(map(lambda c: c.name, category.get_sub_categorys()))
        article_list = Article.objects.filter(category__name__in=categorynames, status='p', is_removed=False)
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        cache_key = 'category_list_{categoryname}_{page}'.format(categoryname=categoryname, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):

        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        kwargs['page_type'] = CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView, self).get_context_data(**kwargs)


class AuthorDetailView(ArticleListView):
    '''
    Author details page
    '''
    page_type = 'Author Article Archive'

    def get_queryset_cache_key(self):
        author_name = self.kwargs['author_name']
        cache_key = 'author_{author_name}_{page}'.format(author_name=author_name, page=self.page_number)
        return cache_key

    def get_queryset_data(self):
        author_name = self.kwargs['author_name']
        article_list = Article.objects.filter(author__username=author_name, type='a', status='p', is_removed=False)
        return article_list

    def get_context_data(self, **kwargs):
        author_name = self.kwargs['author_name']
        kwargs['page_type'] = AuthorDetailView.page_type
        kwargs['tag_name'] = author_name
        return super(AuthorDetailView, self).get_context_data(**kwargs)


class TagDetailView(ArticleListView):
    '''
    Label list page
    '''
    page_type = 'Category tag archive'

    def get_queryset_data(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        article_list = Article.objects.filter(tags__name=tag_name, type='a', status='p', is_removed=False)
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        cache_key = 'tag_{tag_name}_{page}'.format(tag_name=tag_name, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):
        # tag_name = self.kwargs['tag_name']
        tag_name = self.name
        kwargs['page_type'] = TagDetailView.page_type
        kwargs['tag_name'] = tag_name
        return super(TagDetailView, self).get_context_data(**kwargs)


class ArchivesView(ArticleListView):
    '''
    Article archive page
    '''
    page_type = 'Article Archive'
    paginate_by = None
    page_kwarg = None
    template_name = 'blog/article_archives.html'

    def get_queryset_data(self):
        return Article.objects.filter(status='p',is_removed=False).all()

    def get_queryset_cache_key(self):
        cache_key = 'archives'
        return cache_key


class LinkListView(ListView):
    model = Links
    template_name = 'blog/links_list.html'

    def get_queryset(self):
        return Links.objects.filter(is_enable=True)


@csrf_exempt
def fileupload(request):
    """
    This method requires you to write the calling end to upload pictures. This method only provides the picture bed function.
    :param request:
    :return:
    """
    if request.method == 'POST':
        sign = request.GET.get('sign', None)
        if not sign:
            return HttpResponseForbidden()
        if not sign == get_md5(get_md5(settings.SECRET_KEY)):
            return HttpResponseForbidden()
        response = []
        for filename in request.FILES:
            timestr = datetime.datetime.now().strftime('%Y/%m/%d')
            imgextensions = ['jpg', 'png', 'jpeg', 'bmp']
            fname = u''.join(str(filename))
            isimage = len([i for i in imgextensions if fname.find(i) >= 0]) > 0
            blogsetting = get_blog_setting()

            basepath = r'{basedir}/{type}/{timestr}'.format(basedir=blogsetting.resource_path,
                                                            type='files' if not isimage else 'image', timestr=timestr)
            if settings.TESTING:
                basepath = settings.BASE_DIR + '/uploads'
            url = 'https://resource.lylinux.net/{type}/{timestr}/{filename}'.format(
                type='files' if not isimage else 'image', timestr=timestr, filename=filename)
            if not os.path.exists(basepath):
                os.makedirs(basepath)
            savepath = os.path.join(basepath, filename)
            with open(savepath, 'wb+') as wfile:
                for chunk in request.FILES[filename].chunks():
                    wfile.write(chunk)
            if isimage:
                from PIL import Image
                image = Image.open(savepath)
                image.save(savepath, quality=20, optimize=True)
            response.append(url)
        return HttpResponse(response)

    else:
        return HttpResponse("only for post")


@login_required
def refresh_memcache(request):
    try:

        if request.user.is_superuser:
            from teknusa.utils import cache
            if cache and cache is not None:
                cache.clear()
            return HttpResponse("ok")
        else:
            return HttpResponseForbidden()
    except Exception as e:
        logger.error(e)

templates/blog/tags/article_comment.html
{% load blogs_info %}
{% load static %}
    <div class="comments-area">
									
            <h2 class="title" id="comment">{{ total_comments }} comments</h2>
            <ol>
                
                <li class="single_comment_area" id="comment_list">
                        <!-- Comment Content -->
                        
                        {% for comment in comments %} 
                        <div  class="user d-flex mb-4 mt-4"  id="root_{{ comment.pk }}">
                            <!-- Comment Author -->
                            {% ifequal comment.user.username 'reborn' %}
                            <div class="thumb">
                                <img src="{% static 'app/img/comment/comment_2.png' %}" alt="{{ comment.user.username }}">
                            </div>
                            {% else %}
                            <div class="thumb">
                                <img src="{% static 'app/img/comment/comment_2.png' %}" alt="{{ comment.user.username }}">
                            </div>
                            {% endifequal %}
                            <!-- Comment Meta -->
                            <div class="desc" id="comment_{{ comment.pk }}">
                                {% ifequal reply.user.username 'reborn' %}
                                <h5>Blogger</h5>
                                {% else %}
                                <h5>{{ comment.user.username }}</h5>
                                {% endifequal %}
                                <div class="">
                                    <p id="comment_{{ comment.pk }}" class="comment">{{ comment.text|safe }}</p>
                                </div>
                                        <div class="d-flex justify-content-between">
                                            <div class="d-flex align-items-center">
                                                <p class="date">{{ comment.comment_time| timesince}} ago </p>
                                            </div>
                                            <div class="reply-btn">
                                                <a href="#" class="btn-reply text-uppercase">like</a>
                                            </div>
                                            <div class="reply-btn">
                                                <a href="javascript:reply({{ reply.pk }})" class="btn-reply text-uppercase">reply</a>
                                            </div>
                                        </div>
                                   
                            </div>
                        </div>
                        {% if reply.user.username is  null %}
                        <ol class="children">
                        {% for reply in comment.root_comment.all %}
                            <li class="single_comment_area">
                                <!-- Comment Content -->
                                <div class="user d-flex d-flex mb-4">
                                    <!-- Comment Author -->
                                    {% ifequal reply.user.username 'reborn' %}
                                    <div class="thumb">
                                        <img src="{% static 'app/img/comment/comment_2.png' %}" alt="{{ reply.user.username }}">
                                    </div>
                                    {% else %}
                                    <div class="thumb">
                                        <img src="{% static 'app/img/comment/comment_2.png' %}" alt="{{ reply.user.username }}">
                                    </div>
                                    {% endifequal %}
                                    <!-- Comment Meta -->
                                    <div class="desc" id="comment_{{ reply.pk }}">
                                        {% ifequal reply.user.username 'reborn' %}
                                        <h5>Blogger</h5>
                                        {% else %}
                                        <h5>{{ reply.user.username }}-
                                            {% ifequal reply.reply_to.username 'reborn' %}
                                            Blogger
                                            {% else %}
                                            {{ reply.reply_to.username }}
                                            {% endifequal %}
                                        </h5>
                                        {% endifequal %}
                                        <div class="">
                                            <p id="comment_{{ reply.pk }}" class="comment">{{ reply.text|safe }}</p>
                                        </div>
                                        <div class="d-flex justify-content-between">
                                            <div class="d-flex align-items-center">
                                                <p class="date">{{ reply.comment_time| timesince}} ago </p>
                                            </div>
                                            <div class="reply-btn">
                                                <a href="#" class="btn-reply text-uppercase">like</a>
                                            </div>
                                            <div class="reply-btn">
                                                <a href="javascript:reply({{ reply.pk }})" class="btn-reply text-uppercase">reply</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                            </ol>
                        {% endif %}

                    {% empty %}
                    There are no comments for this article. Just say a few words!
                    {% endfor %}  
                    </li>
                </ol>
            </div>

templates/blog/tags/article_comment_form.html
    {% load blogs_info %}
    <div class="comment-form">
            <h2 class="mb-4">Leave A Comment</h2>
                {% if user.is_authenticated %}
                    <form id = "comment_form" action="{% url 'comment:update_comment' %}" class="form-contact comment_form" method="POST">

                        <div id="reply_content_container" style="display:none;">
                            <p id="reply_title">Reply：</p>
                            <div id="reply_content"></div>
                        </div>

                        {% csrf_token %}
                        {% get_comment_form artilce as comment_form %}
                        {% for field in comment_form %}
                            {{ field }}
                        {% endfor %}

                        <span id="comment_error" class="text-danger pull-left"></span>
                        <input class="btn btn-primary pull-right" type="submit" value="comment">
                    </form>
                {% else %}
                    Please login and comment
                    <a class = "btn btn-primary" href="{% url 'login' %}?from={{ request.get_full_path }}">log in</a>
                    <span> or </span>
                    <a class = "btn btn-danger" href="{% url 'register' %}?from={{ request.get_full_path }}">register</a>
                {% endif %}
            
        </div>

templates/blog/tags/article_detail_info.html
{% load blogs_info %}
{% load static %}
{% load cache %}

<div class="single-post">
   <div class="blog_details">
        <div>
            <textarea id="textToSpeech" hidden>{{ article.body|custom_markdown|striptags}}</textarea>
        </div>
        <ul>
         {% load_article_metas article user True %}
        </ul>
      <p class="excert">
        {{ article.body|custom_markdown }}
        </p>
      <p class='tagcloud'>
            {% if article.type == 'a' %}
                {% if article.tags.all %}
                    {% for t in article.tags.all %}
                        <a href=' {{ t.get_absolute_url }}' rel="tag" title="View all articles tagged with {{ t.name }}">{{ t.name }}</a>
                    {% endfor %}
                {% endif %}
            {% endif %}
            </p>
   </div>
</div>

templates/blog/tags/breadcrumb.html
<div class="breadcrumb mb-5">
    
        
    {% for name,url in names %}
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">

            <a href="{{ url }}" itemprop="url">
                <span itemprop="title"> {{ name }}</span>
            </a>&nbsp;&rsaquo;

        </div>
    {% endfor %}
    {{ title }}
</div>

templates/blog/tags/sidebar.html
{% load blogs_info %}
{% load static %}
{% block compress_css %}
<style>
    .post_item img {
        width:120px;
        height:100px;
    }
</style>

{% endblock %}
<div id="secondary" class="widget-area" role="complementary">
    {% if extra_sidebars %}
        {% for sidebar in extra_sidebars %}

            <aside class="widget_text widget widget_custom_html"><h3 class="widget-title">
                {{ sidebar.name }}</h3>
                <div class="textwidget custom-html-widget">
                    {{ sidebar.content|custom_markdown }}
                </div>
            </aside>
        {% endfor %}
    {% endif %}
    {% if most_read_articles %}
        <aside class="single_sidebar_widget popular_post_widget" id="recent-posts-2">
                            <h3 class="widget_title">Most Read Posts</h3>
                            {% for a in most_read_articles %}
                            <div class="media post_item">
                                {% markdown_images a.body as imgs %}
                                {% if imgs %}
                                    <img src="{{ imgs.0 }}" alt="{{ a.title }}">
                                {% endif %}
                                <div class="media-body">
                                    <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                                        <h3>{{ a.title }}...</h3>
                                    </a>
                                    <p>{{ a.body|custom_markdown|escape|truncate|slice:80 }}...</p>
                                    <p class="mt-3"><i class="fas fa-eye"></i> {{ a.views }}</p>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </aside>
        
    {% endif %}
    {% if sidebar_categorys %}
    <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                            {% for c in sidebar_categorys %}
                                <li>
                                    <a href="{{ c.get_absolute_url }}" class="d-flex">
                                        <p>{{ c.name }}</p>
                                    </a>
                                </li>
                                
                                {% endfor %}
                            </ul>
                        </aside>
        
    {% endif %}
    {% if sidebar_comments and  open_site_comment %}
        <aside id="ds-recent-comments-4" class="widget ds-widget-recent-comments"><h3 class="widget-title">Recent comments</h3>
            {% comment %}<ul class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1"
            data-show-title="1" data-show-admin="1" data-avatar-size="30" data-excerpt-length="70"></ul>{% endcomment %}
            <ul id="recentcomments">
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                <span class="comment-author-link">
                    {{ c.author.username }}</span>
                        published in
                        <a href="{{ c.article.get_absolute_url }}#comment-{{ c.pk }}">{{ c.article.title }}</a>》
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if recent_articles %}
    <aside class="single_sidebar_widget popular_post_widget" id="recent-posts-2">
                            <h3 class="widget_title">Recent Post</h3>
                            {% for a in  recent_articles %}
                            <div class="media post_item">
                                {% markdown_images a.body as imgs %}
                                {% if imgs %}
                                    <img src="{{ imgs.0 }}" alt="{{ a.title }}">
                                {% endif %}
                                <div class="media-body">
                                    <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                                        <h3>{{ a.title }}...</h3>
                                    </a>
                                    <p>{{ a.body|custom_markdown|escape|truncate|slice:70 }}...</p>
                                    <p class="mt-3"><i class="fas fa-upload"></i> {{ a.pub_time|timesince }} ago</p>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </aside>
       
    {% endif %}
    {% if sidabar_links %}
        <aside id="linkcat-0" class="widget widget_links"><h3 class="widget-title">Bookmark</h3>
            <ul class='xoxo blogroll'>
                {% for l in sidabar_links %}
                    <li>
                        <a href="{{ l.link }}" target="_blank" title="{{ l.name }}">{{ l.name }}</a>
                    </li>
                {% endfor %}

            </ul>
        </aside>
    {% endif %}
    {% if show_google_adsense %}
        <aside id="text-2" class="widget widget_text"><h3 class="widget-title">Google AdSense</h3>
            <div class="textwidget">
                {{ google_adsense_codes|safe }}
            </div>
        </aside>
    {% endif %}
    {% if sidebar_tags %}
    <aside class="single_sidebar_widget tag_cloud_widget">
                            <h4 class="widget_title">Popular tags</h4>
                            <ul class="list">
                            
                            {% for tag,count,size in sidebar_tags %}
                                <li>
                                    <a href="{{ tag.get_absolute_url }}" title="{{ count }} {{ tag.name }}">{{ tag.name }} ({{ count }})</a>
                                </li>
                            {% endfor %}
                            </ul>
                        </aside>
        
    {% endif %}
    <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                            <li><a href="/admin/" class="d-flex" rel="nofollow">Admin</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout' %}" class="d-flex" rel="nofollow">Sign out</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'accounts:login' %}" class="d-flex" rel="nofollow">log in</a>
                            {% endif %}
                            {% if user.is_superuser %}
                                <li><a href="{% url 'blog:refresh' %}" class="d-flex" target="_blank">Refresh the cache</a></li>
                    
                            {% endif %}
                            </ul>
                        </aside>
    
</div><!-- #secondary -->