apps/careers/urls.py
from django.urls import path,include
from careers.views.admin_view import *
from careers.views.apply_view import *
from careers.views.jobs_view import *
from careers.apiview import JobsListing

app_name = "careers"
urlpatterns = [
    path('careers/', include([
        path("filter/", JobsListing.as_view(), name = 'listing'),
        path('', JobView.as_view(), name='careers'),
        path(r'<int:year>/<int:month>/<int:day>/<int:job_id>/<slug:slug>.html', JobDetailsView.as_view(), name='job_description'),
        path(r'applicants/<int:job_id>/job_apply.html', JobApplyView.as_view(), name='job_apply'),
        path('search', SearchView.as_view(), name='search'),
        path('employer/dashboard/', include([
            path('', DashboardView.as_view(), name='employer-dashboard'),
            path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
            path('applicants/<int:job_id>', ApplicantsperJobView.as_view(), name='employer-dashboard-applicants'),
            path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        ])),
        path('admin/', include([
            path('applicant/<int:applicant_id>/<slug:slug>', ApplicantsDetailsView.as_view(), name='job_applicant_details'),
        ])),
    ])),
    # path('apply-job/<int:job_id>', careers.views.ApplyJobView.as_view(), name='apply-job'),
    
]

apps/home/urls.py
from django.urls import path,include
from .views import *
app_name = "home"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

teknusa/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include, re_path
from accounts import views
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from teknusa.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from teknusa.feeds import AgrositeFeed
from django.views.generic import TemplateView
from ckeditor_uploader import urls as ckeditor_urls
from ckeditor_uploader import views as ckeditor_uploader_views


sitemaps = {
    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handler403 = 'blog.views.permission_denied_view'  # perbaiki typo: handle403 -> handler403

urlpatterns = [
    path('admin/', admin.site.urls),   # <--- tambahkan ini

    path('mdeditor/', include('mdeditor.urls')),
    path('cookies/', include('cookie_consent.urls')),
    # path('', include('notice.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('home.urls')),
    path('', include('apps.contactus.urls')),
    path('', include('about.urls')),
    # path('', include('apps.careers.urls')),
    path('', include('services.urls')),
    path('', include('portfolio.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path("likes/", include(('likeunlike.urls', 'likeunlike'), namespace="likes")),
    path('summernote/', include('django_summernote.urls')),

    # sitemap pakai re_path karena regex
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    path('feed/', AgrositeFeed()),
    path('rss/', AgrositeFeed()),
    path('comment/', include('comment.urls')),
    path('', include('accounts.urls', namespace='account')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('lean/', include('lean.urls')),
    path('ledger/', include('ledger.urls')),
    path('post_media/', include('post_media.urls')),
    path('search/', include('haystack.urls'), name='search'),
    path('ckeditor/', include(ckeditor_urls)),  # Ensure ckeditor URLs are included
    path('ckeditor/upload/', ckeditor_uploader_views.upload, name='ckeditor_upload'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/careers/views/jobs_view.py

from django.shortcuts import render
from datetime import datetime
from django.contrib.auth.models import User
from django.http import Http404
# Create your views here.
from django.views.generic import ListView,DetailView
from careers.models import Job
import django.utils.timezone as timezone

class JobDetailsView(DetailView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'job_id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        else:
            obj.viewed()
            self.object = obj
        return obj

    # def get_object(self, queryset=None):
    #     obj = super(JobDetailsView, self).get_object(queryset=queryset)
    #     if obj is None:
    #         raise Http404("Job doesn't exists")
    #     return obj

    def get_context_data(self, **kwargs):
        job_id = int(self.kwargs[self.pk_url_kwarg])
        user = self.request.user
        
        kwargs['next_job'] = self.object.next_job
        kwargs['prev_job'] = self.object.prev_job

        return super(JobDetailsView, self).get_context_data(**kwargs)

    # def get(self, request, *args, **kwargs):
    #     try:
    #         self.object = self.get_object()
    #     except Http404:
    #         # redirect here
    #         raise Http404("Job doesn't exists")
    #     context = self.get_context_data(object=self.object)
    #     return self.render_to_response(context)

class JobView(ListView):
    model = Job
    template_name = 'jobs/home.html'
    context_object_name = 'jobs'
    extra_context = {
        'title': 'career'
    }
    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context



class SearchView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         title__contains=self.request.GET['position'])




apps/home/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from datetime import datetime
# Create your views here.
from django.views.generic import ListView,DetailView, CreateView
from blog.models import Article
from .models import  Messages
from portfolio.models import Portfolio
# Create your views here.
class HomeListView(ListView):
    template_name = 'main/index.html'  
    context_object_name = 'home'           
    extra_context={
        'title':'Home Page',
        'year':datetime.now().year,
    }
    def get_context_data (self, ** kwargs):
        context = super (). get_context_data (** kwargs)
        context ['blogs'] = Article.objects.filter(status='p')
        context ['portfolios'] = Portfolio.objects.all().filter()
        return context
        
    def get_queryset(self):
        return Portfolio.objects.all()
    
class HomeView(HomeListView):
    pass


def messages(request):
    messages = Messages.objects.get(pk=1)
    return render(request, 'blog/messages.html', {'messages': messages})

extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.remote_field, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):

templates/jobs/details.html
{% extends 'main/layout.html' %}
{% load static %}
{% load blogs_info %}
{% load job_tags %}
{% block meta %}
    <title>{{ job.title }} | {{ SITE_DESCRIPTION }}</title>
    
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ job.title }}"/>

    <meta property="og:description" content="{{ job.description|custom_markdown|striptags|truncatewords:8 }}"/>
    <meta property="og:url"
          content="{{ job.get_full_url }}"/>
    <meta property="article:published_time" content="{% datetimeformat job.created_at %}"/>
    <meta property="article:modified_time" content="{% datetimeformat job.modified_at %}"/>
    <meta property="article:author" content="{{ job.user.get_full_url }}"/>
    <meta property="article:section" content="{{ job.jobcategory.name }}"/>
    
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

    <meta name="description" content="{{ job.description|custom_markdown|striptags|truncatewords:8 }}"/>
    
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    
    <meta property="og:image" content="{{ job.cover }}" />
    
    <meta property="og:image:alt" content="{{ job.title }}" />
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="{{ SITE_NAME }}">
    <meta name="twitter:title" content="{{ job.title }}">
    <meta name="twitter:description" content="{{ job.description|custom_markdown|striptags|truncatewords:8 }}">
    <meta name="twitter:creator" content="{{ SITE_NAME }}">
    
    <meta name="twitter:image:src" content="{{ job.cover }}">
    
    <meta name="twitter:image:alt" content="{{ job.title }}" />
    <meta name="twitter:domain" content="www.agrowdev.com">
{% endblock %}
{% block compress_css %}
    <link rel="stylesheet" href="{% static 'careers/styles.css' %}">
    <link rel="stylesheet" href="{% static 'careers/styles.css' %}">
{% endblock %}
{% block content %}

    <section class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                
                  <div class="job_details_header mt-5 mb-5">
                        {% load_jobs_baseinfo job user True %}
                    </div>
                    {% load_job_detail_info job request.user %}
                    
                </div>
                <div class="col-lg-4">
                    <div class="post-details3  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Job Overview</h4>
                           </div>
                          <ul>
                              <li>Posted date : <span>{{job.created_at|date}}</span></li>
                              <li>Location : <span>{{job.location}}</span></li>
                              <li>Vacancy : <span>02</span></li>
                              <li>Job nature : <span>{% if job.jobtype == '1' %}
                                                        Full time
                                                    {% elif job.jobtype == '2' %}
                                                        Part time
                                                    {% else %}
                                                        Internship
                                                    {% endif %}</span></li>
                              <li>Salary :  <span>{{job.salary}} Monthly</span></li>
                              <li>Application date : <span>{{job.last_date|date}}</span></li>
                          </ul>
                         <div class="apply-btn2">
                            <a href="{% url 'careers:job_apply' job_id=job.id %}" class="boxed-btn3 ">Apply Now</a>
                         </div>
                       </div>
                    
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

templates/jobs/jobs.html
{% extends 'main/layout.html' %}
{% load blogs_info %}
{% load static %}
{% block meta %}
    {% if tag_name %}
        <title>{{ page_type }}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} Blogs | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta name="robots" content="index, follow">
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
    <meta property="og:image" content="https://www.herokucdn.com/images/og.png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
{% endblock %}
{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <div class="job-page-tittle text-center">
                <h2 class="heading">Find a <span class="accent">job</span> you will
                    <span class="accent">love</span>.
                </h2>
            </div>
            <div class="col-lg-8 mx-auto">
            <form id="job-main-form" method="get" class="form-contact contact_form" action="{% url 'careers:search' %}">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">Position</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="single-input-primary form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="single-input-primary form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" class="genric-btn info radius"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
        </div>
    </section>
    <section class="negative-margin-100">
        <div class="container">
            <div class="job-page-tittle text-center">
                <h2 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs
                </h2>
            </div>
            
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'app/img/jobs/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a
                                            href="{% url 'careers:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <p class="job__company">
                                        {{ job.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ job.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ job.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}