apps/careers/urls.py
from django.urls import path,include
from careers.views.admin_view import *
from careers.views.apply_view import *
from careers.views.jobs_view import *
from careers.apiview import JobsListing

app_name = "careers"
urlpatterns = [
    path('careers/', include([
        path("filter/", JobsListing.as_view(), name = 'listing'),
        path('', JobView.as_view(), name='careers'),
        path(r'<int:year>/<int:month>/<int:day>/<int:job_id>/<slug:slug>.html', JobDetailsView.as_view(), name='job_description'),
        path(r'applicants/<int:job_id>/job_apply.html', JobApplyView.as_view(), name='job_apply'),
        path('search', SearchView.as_view(), name='search'),
        path('employer/dashboard/', include([
            path('', DashboardView.as_view(), name='employer-dashboard'),
            path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
            path('applicants/<int:job_id>', ApplicantsperJobView.as_view(), name='employer-dashboard-applicants'),
            path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        ])),
        path('admin/', include([
            path('applicant/<int:applicant_id>/<slug:slug>', ApplicantsDetailsView.as_view(), name='job_applicant_details'),
        ])),
    ])),
    # path('apply-job/<int:job_id>', careers.views.ApplyJobView.as_view(), name='apply-job'),
    
]

apps/likeunlike/urls.py
from django.urls import path
from .apiview import (
    LikeListAPIView,
    UserCountOfLikesAPIView,
    LikeToggleView,
    IsLikedAPIView,
)

app_name = 'likes-api'

urlpatterns = [
    path('likes/list/', LikeListAPIView.as_view(), name='list'),
    path('likes/count/', UserCountOfLikesAPIView.as_view(), name='count'),
    path('likes/toggle/', LikeToggleView.as_view(), name='toggle'),
    path('likes/is/', IsLikedAPIView.as_view(), name='is'),
]

teknusa/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include, re_path
from accounts import views
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from teknusa.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from teknusa.feeds import AgrositeFeed
from django.views.generic import TemplateView
from ckeditor_uploader import urls as ckeditor_urls
from ckeditor_uploader import views as ckeditor_uploader_views


sitemaps = {
    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handler403 = 'blog.views.permission_denied_view'  # perbaiki typo: handle403 -> handler403

urlpatterns = [
    path('admin/', admin.site.urls),   # <--- tambahkan ini

    path('mdeditor/', include('mdeditor.urls')),
    path('cookies/', include('cookie_consent.urls')),
    # path('', include('notice.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('home.urls')),
    path('', include('apps.contactus.urls')),
    path('', include('about.urls')),
    # path('', include('apps.careers.urls')),
    path('', include('services.urls')),
    path('', include('portfolio.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path("likes/", include(('likeunlike.urls', 'likeunlike'), namespace="likes")),
    path('summernote/', include('django_summernote.urls')),

    # sitemap pakai re_path karena regex
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    path('feed/', AgrositeFeed()),
    path('rss/', AgrositeFeed()),
    path('comment/', include('comment.urls')),
    path('', include('accounts.urls', namespace='account')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('lean/', include('lean.urls')),
    path('ledger/', include('ledger.urls')),
    path('post_media/', include('post_media.urls')),
    path('search/', include('haystack.urls'), name='search'),
    path('ckeditor/', include(ckeditor_urls)),  # Ensure ckeditor URLs are included
    path('ckeditor/upload/', ckeditor_uploader_views.upload, name='ckeditor_upload'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/careers/views/jobs_view.py

from django.shortcuts import render
from datetime import datetime
from django.contrib.auth.models import User
from django.http import Http404
# Create your views here.
from django.views.generic import ListView,DetailView
from careers.models import Job
import django.utils.timezone as timezone

class JobDetailsView(DetailView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'job_id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        else:
            obj.viewed()
            self.object = obj
        return obj

    # def get_object(self, queryset=None):
    #     obj = super(JobDetailsView, self).get_object(queryset=queryset)
    #     if obj is None:
    #         raise Http404("Job doesn't exists")
    #     return obj

    def get_context_data(self, **kwargs):
        job_id = int(self.kwargs[self.pk_url_kwarg])
        user = self.request.user
        
        kwargs['next_job'] = self.object.next_job
        kwargs['prev_job'] = self.object.prev_job

        return super(JobDetailsView, self).get_context_data(**kwargs)

    # def get(self, request, *args, **kwargs):
    #     try:
    #         self.object = self.get_object()
    #     except Http404:
    #         # redirect here
    #         raise Http404("Job doesn't exists")
    #     context = self.get_context_data(object=self.object)
    #     return self.render_to_response(context)

class JobView(ListView):
    model = Job
    template_name = 'jobs/home.html'
    context_object_name = 'jobs'
    extra_context = {
        'title': 'career'
    }
    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context



class SearchView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         title__contains=self.request.GET['position'])




templates/jobs/tags/job_applicants.html
    <div class="col-md-4">
        <div class="outer-div">
        <div class="inner-div">
            <div class="front">
                <div class="card-container">
                    <span class="pro">Applied {{ applicant.created_at.astimezone }}</span>
                    <img class="round" src="{{ applicant.cover.url }}" alt="{{ applicant.fullnamename }}" />
                    <h3>{{ applicant.fullnamename }}</h3>
                    <h6>{{ applicant.location }}</h6>
                    <p>{{ applicant.job.title }}</p>
                    <div class="buttons">
                        <button class="primary">
                            Message
                        </button>
                        <button class="primary ghost">
                            Following
                        </button>
                    </div>
                    <div class="skills">
                        <h6>Skills</h6>
                        <ul>
                            <li>UI / UX</li>
                            <li>Front End Development</li>
                            <li>HTML</li>
                            <li>CSS</li>
                            <li>JavaScript</li>
                            <li>React</li>
                            <li>Node</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="back">
            <div class="social-media-wrapper">
                {% if applicant.facebook %}
                    <a href="{{ applicant.facebook }}" class="social-icon"><i class="fa ti-facebook"></i></a>
                {% endif %}
                {% if applicant.twitter %}
                    <a href="{{ applicant.twitter }}" class="social-icon"><i class="fa ti-twitter"></i></a>
                {% endif %}
        
                {% if applicant.instagram %}
                    <a href="{{ applicant.instagram }}" class="social-icon"><i class="fa ti-instagram"></i></a>
                {% endif %}
                {% if applicant.github %}
                    <a href="{{ applicant.github }}" class="social-icon"><i class="fa ti-github"></i></a>
                {% endif %}
                {% if applicant.linkedin %}
                    <a href="{{ applicant.linkedin }}" class="social-icon"><i class="fa ti-linkedin"></i></a>
                {% endif %}
                
                <a href="{{ applicant.get_absolute_url }}" class="genric-btn info circle float-right" ><i class="fa ti-long-arrow-right "></i>View More</a>
                  
            </div>
            </div>
        </div>
    </div>
    </div>
            {% comment %} <div class="col-md-4">
                        <div class="single-team-slide">
                            <img height="350" src="{{ applicant.cover.url }}" alt="{{ applicant.fullnamename }}">
                            <!-- Overlay Effect -->
                            <div class="overlay-effect">
                                <h6>{{ applicant.job.title }}</h6>
                                <h4>{{ applicant.fullname }}</h4>
                                <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                                </p>
                                <p>{{ applicant.degree_college }}<br>{{ applicant.location }}
                                <br>{{ applicant.university }}<br>{{ applicant.degree_marks }}</p>
                                
                            </div>
                            <!-- Social Info -->
                            <div class="team-social-info">
                                {% if applicant.facebook %}
                                    <a href="{{ applicant.facebook }}" class="facebook" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa ti-facebook"></i></a>
                                {% endif %}
                                {% if applicant.twitter %}
                                    <a href="{{ applicant.twitter }}" class="twitter" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa ti-twitter"></i></a>
                                {% endif %}
        
                                {% if applicant.instagram %}
                                    <a href="{{ applicant.instagram }}" class="instagram" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa ti-instagram"></i></a>
                                {% endif %}
                                {% if applicant.github %}
                                    <a href="{{ applicant.github }}" class="github" data-toggle="tooltip" data-placement="top" title="GitHub"><i class="fa ti-github"></i></a>
                                {% endif %}
                                {% if applicant.linkedin %}
                                    <a href="{{ applicant.linkedin }}" class="twitter" data-toggle="tooltip" data-placement="top" title="linkedin"><i class="fa ti-linkedin"></i></a>
                                {% endif %}
                                
                                <a href="{{ applicant.get_absolute_url }}" class="genric-btn info circle float-right" ><i class="fa ti-long-arrow-right "></i>View More</a>
                                
                            </div>
                        </div>
                    </div> {% endcomment %}

templates/jobs/tags/job_base.html
{% load blogs_info %}
{% load likes_tags %}
{% load static %}
{% csrf_token %}


                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <a href="{{ job.get_absolute_url }}">
                                                <img src="{{job.cover.url}}" height=60 width=60 alt="job.title">
                                            </a>
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{{ job.get_absolute_url }}"><h4>{{ job.title }}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{ job.location }}</p>
                                                </div>
                                                <div class="location">
                                                    {% if job.jobtype == '1' %}
                                                        <span class="badge featured-badge badge-success">Full time</span>
                                                    {% elif job.jobtype == '2' %}
                                                        <span class="badge featured-badge badge-primary">Part time</span>
                                                    {% else %}
                                                        <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                                    {% endif %}
                                                </div>
                                                <div class="location">
                                                    <p>RS {% if job.salary > 0 %} {{ job.salary }}{% else %} Negotiable {% endif %}</p>
                                                </div>
                                                <div class="location">
                                                    <p>Likes <span id="likes_count">{{ job|likes_count }}</span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            
                                            {% content_type job as ct %}
                                            
                                                <form  id="like" action="{% url 'likes-api:toggle' %}" method="POST">
                                                    {% csrf_token %}
                                                    <input name="id" type="hidden" value="{{job.id}}">
                                                    <input name="content_type" type="hidden" value="{{ct}}">
                                                </form>
                                            <a class="heart_mark" id="save"><i class="fa ti-heart"></i> </a>
                                            
                                            {% if not isdetail %}
                                                <a href="{{ job.get_absolute_url }}" class="boxed-btn3">View Details </a>
                                            {% endif %}
                                        </div>
                                        <div class="date">
                                            <p>Last Date:{{ job.last_date|date }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

templates/jobs/tags/job_details.html
{% load blogs_info %}
{% load job_tags %}
<p>{{ job.description| custom_markdown | safe}}</p>
 {% if user.is_authenticated %}
                        {% is_already_applied job user as is_applied %}
                        {% if is_applied %}
                            <a href="" class="genric-btn info large"> Already Applied</a>
                        {% else %}
                            <div class="job-detail__apply-bottom">
                                    <a href="{% url 'careers:job_apply' job_id=job.id %}" class="genric-btn info large"> Apply for this job</a>
                            </div>
                        {% endif %}
                    {% endif %}

templates/jobs/tags/job_filters.html
                
                        <div class="row">
                            <div class="col-12">
                                    <div class="small-section-tittle2 mb-45">
                                    <div class="ion"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20px" height="12px">
                                    <path fill-rule="evenodd" fill="rgb(27, 207, 107)" d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z"></path>
                                    </svg>
                                    </div>
                                    <h4>Filter Jobs</h4>
                                </div>
                            </div>
                        </div>
                        
                        <div class="job-category-listing mb-50">
                            <!-- single one -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Category</h4>
                               </div>
                                    
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select id="category" name="position" style="display: none;">
                                        <option value="all">All Category</option>
                                        {% for cat in job_categorys %}
                                            <option value="{{cat.pk}}">{{cat.name}}</option>
                                        {% endfor %}
                                    </select><div class="nice-select" tabindex="0"><span class="current">All Category</span>
                                    <ul class="list">
                                    <li data-value="" class="option selected focus">All Category</li>
                                    {% for cat in job_categorys %}
                                        <li data-value="{{cat.pk}}" class="option">{{cat.name}}</li>
                                    {% endfor %}
                                    </ul></div>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div id="jobtype" class="select-Categories pt-80 pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Job Type</h4>
                                    </div>
                                    <label class="container">Full Time
                                        <input type="checkbox" value="1" name="jobtype1">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container" >Part Time
                                        <input type="checkbox" value="2" name="jobtype2">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Internship
                                        <input type="checkbox" value="3" name="jobtype3">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Remote
                                        <input type="checkbox" value="4" name="jobtyp4">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Freelance
                                        <input type="checkbox" value="5" name="jobtype5">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single two -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Location</h4>
                               </div>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select id="location" name="position" style="display: none;">
                                        <option value="all">Anywhere</option>
                                        {% for loc in job_locations %}
                                            <option value="{{loc.pk}}">{{loc.location}}</option>
                                        {% endfor %}
                                    </select><div class="nice-select" tabindex="0"><span class="current">Anywhere</span>
                                    <ul class="list">
                                    <li data-value="" class="option selected focus">Anywhere</li>
                                    {% for loc in job_locations %}
                                        <li data-value="{{loc.pk}}" class="option">{{loc.location}}</li>
                                    {% endfor %}
                                    </ul></div>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Experience</h4>
                                    </div>
                                    <label class="container">1-2 Years
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">2-3 Years
                                        <input type="checkbox" checked="checked active">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">3-6 Years
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">6-more..
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single three -->
                            <div class="single-listing">
                                <!-- select-Categories start -->
                                <div class="select-Categories pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Posted Within</h4>
                                    </div>
                                    <label class="container">Any
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Today
                                        <input type="checkbox" checked="checked active">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 2 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 3 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 5 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 10 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                        </div>
                